env:
  browser: false
  es6: true
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - airbnb-typescript
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - ./tsconfig.json
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
  - prettier
  - import
  - react
reportUnusedDisableDirectives: true
overrides:
  - files:
      - '*.ts, *.js'
    rules:
      default-case: off
      consistent-return: off
rules:
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/no-unsafe-assignment': 'off'
  '@typescript-eslint/no-unsafe-call': 'off'
  '@typescript-eslint/no-unsafe-argument': 'off'

  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  prettier/prettier: ['error', { 'useTabs': false, 'tabWidth': 2 }]
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: local
      varsIgnorePattern: '^[iI]gnored'
      args: after-used
      argsIgnorePattern: '^_|^ignored'
      ignoreRestSiblings: true
      caughtErrors: all
      caughtErrorsIgnorePattern: '^ignored'
  no-param-reassign:
    - error
    - props: false
  import/extensions: off
  import/no-unresolved: off
  import/prefer-default-export: off
  import/order: off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/no-empty-interface': off
  no-underscore-dangle: off
  no-console: off
  '@typescript-eslint/no-use-before-define': off
  no-nested-ternary: off
  '@typescript-eslint/prefer-ts-expect-error': error
  '@typescript-eslint/prefer-optional-chain': error
  '@typescript-eslint/prefer-nullish-coalescing': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-return': error
  '@typescript-eslint/no-explicit-any': off
  no-shadow:
    - error
    - allow:
        - manager
  class-methods-use-this: off
  max-classes-per-file: off
  import/no-cycle: off
  no-await-in-loop: off
  no-restricted-syntax:
    - error
    - selector: ForInStatement
      message: 'for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.'
    - selector: LabeledStatement
      message: 'Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.'
    - selector: WithStatement
      message: '`with` is disallowed in strict mode because it makes code impossible to predict and optimize.'
  new-cap: off
  prefer-destructuring:
    - error
    - array: false
  func-names: off
  no-continue: off
  no-constant-condition: off
  react/jsx-filename-extension:
    - error
    - extensions:
        - .js
        - .jsx
        - .tsx
