semi: true
arrowParens: always
useTabs: true
tabWidth: 4
printWidth: 120
singleQuote: true
jsxSingleQuote: true
trailingComma: all
quoteProps: as-needed
overrides:
  - files:
      - '**/*.yml'
      - '**/*.yaml'
    options:
      useTabs: false
      tabWidth: 2
