import { NextPage } from 'next/types';
import React, { RefObject, useRef } from 'react';
import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import FeaturesHeader from '../components/common/Header/FeaturesHeader';
import Footer from '../components/common/Footer';
import Greetings from '../components/company/Greetings/Greetings';
import Done from '../components/company/Done/Done';
import Counts from '../components/company/Counts/Counts';
import Teamvio from '../components/company/Teamvio/Teamvio';
import Commitments from '../components/company/Commitments/Commitments';
import Role from '../components/company/Role/Role';
import Contact from '../components/company/Contact/Contact';
import styled from 'styled-components';

export async function getStaticProps({ locale }: any) {
	return {
		props: {
			locale,
			...(await serverSideTranslations(locale, ['header', 'features', 'main', 'company'])),
		},
	};
}

const Company: NextPage<any> = (props) => {
	const locale: any = props.locale;

	const contactSection = useRef() as RefObject<HTMLDivElement>;

	const executeScroll = () => {
		if (contactSection.current) {
			scrollTo({
				top: contactSection.current.offsetTop - 100,
				left: 0,
				behavior: 'smooth',
			});
		}
	};

	return (
		<>
			<Main>
				<Head>
					<title>Company</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.svg' />
				</Head>

				<FeaturesHeader locale={locale} Tab='Company' />
				<Greetings scrollDown={executeScroll} />
				<Done />
				<Counts />
				<Teamvio />
				<Commitments />
				<Role />
				<Contact contactSectionRef={contactSection} />
				<Footer background='#ffffff' />
			</Main>
		</>
	);
};

export const Main = styled.main`
	position: relative;
	z-index: 2;
	overflow: hidden;
`;

export default Company;
