import { NextPage } from 'next/types';
import React, { ReactPropTypes } from 'react';
import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import Header from '../components/common/Header/Header';
import Footer from '../components/common/Footer';
import Greetings from '../components/company/Greetings/Greetings';
import Done from '../components/company/Done/Done';
import Counts from '../components/company/Counts/Counts';
import Teamvio from '../components/company/Teamvio/Teamvio';
import Commitments from '../components/company/Commitments/Commitments';
import Role from '../components/company/Role/Role';
import Contact from '../components/company/Contact/Contact';
import styled from 'styled-components';

export async function getStaticProps({ locale }: any) {
	return {
		props: {
			locale,
			...(await serverSideTranslations(locale, ['home'])),
		},
	};
}

const Company: NextPage<ReactPropTypes> = (props) => {
	const locale = props.locale;
	return (
		<>
			<Main>
				<Head>
					<title>Company</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.svg' />
				</Head>

				<Header locale={locale} Tab='Company' />

				<section>
					<Greetings />
					<Done />
					<Counts />
					<Teamvio />
					<Commitments />
					<Role />
					<Contact />
				</section>

				<Footer background='#ffffff' />
			</Main>
		</>
	);
};

export const Main = styled.main`
	position: relative;
	z-index: 2;
	overflow: hidden;
`;

export default Company;
