import { NextPage } from 'next/types';
import React, { ReactPropTypes } from 'react';
import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import Header from '../components/common/Header/Header';
import RedTopSquare from '../components/main/RedTopSquare/RedTopSquare';
import { Container } from '../components/common/Container/Container';
import { Main } from '../components/main/styles';
import { GreySquare, GreySquareDots } from '../components/main/GreyTopSquare/GreyTopSquare';
import Preview from '../components/main/Preview/Preview';
import HowItWorks from '../components/main/HowItWorks/HowItWorks';
import MoreMoney from '../components/main/MoreMoney/MoreMoney';
import FeaturedOn from '../components/main/FeaturedOn/FeaturedOn';
import WhyChoose from '../components/main/WhyChoose/WhyChoose';
import Smile from '../components/main/Smile/Smile';
import FormFilling from '../components/main/FormFilling/FormFilling';
import Footer from '../components/common/Footer';

export async function getStaticProps({ locale }: any) {
	return {
		props: {
			locale,
			...(await serverSideTranslations(locale, ['home'])),
		},
	};
}

const Home: NextPage<ReactPropTypes> = (props) => {
	const locale = props.locale;
	return (
		<>
			<RedTopSquare />
			<GreySquare top='-182px' left='642px' size='256.75px' />
			<GreySquare top='410px' left='212px' size='343.78px'>
				<GreySquareDots src='/images/main/preview/dots-under-text.png' alt='' />
			</GreySquare>

			<Main>
				<Head>
					<title>Home</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.svg' />
				</Head>

				<Header locale={locale} Tab='Home' />

				<section>
					<Container>
						<Preview />
					</Container>
					<HowItWorks />
					<MoreMoney />
					<FeaturedOn />
					<WhyChoose />
					<Smile />
					<FormFilling />
					<Footer background='#ffffff' />
				</section>
			</Main>
		</>
	);
};

export default Home;
